// Terms of art, kept because planners and textbooks use them, each with a one-line plain meaning shown on hover.
export const GLOSSARY: Record<string, string> = {
  ATP: "Available to promise: stock and incoming supply not yet promised to any customer.",
  CTP: "Capable to promise: what could still be made, bought or moved in time if the stock isn't there.",
  BOP: "Backorder processing: re-deciding who gets scarce stock first after a shortage.",
  RLT: "Replenishment lead time: after this, any quantity can be promised because it could be made or bought in time.",
  MRP: "Material requirements planning: working out what to make and buy from demand, stock and bills of material.",
  DRP: "Distribution requirements planning: the same netting for what to move between locations.",
  "S&OP": "Sales and operations planning: a month-by-month plan that balances demand against capacity and supply limits.",
  MEIO: "Multi-echelon inventory optimisation: placing safety stock across the whole network at the least cost for the service promised.",
  DDMRP: "Demand-driven MRP: stock buffers with green, yellow and red zones that trigger orders.",
  WAPE: "Weighted absolute percentage error: forecast error across all series, weighted by volume. Lower is better.",
  Bias: "Whether the forecast tends to be too high (positive) or too low (negative).",
  FVA: "Forecast value added: how much better the forecast is than simply repeating last period.",
  OTIF: "On time, in full: orders delivered complete by the date agreed.",
  EOQ: "Economic order quantity: the order size that balances ordering cost against the cost of holding stock.",
  BOM: "Bill of material: the components and quantities that go into one unit of a product.",
  "Safety stock": "Extra stock held to cover demand and supply surprises.",
  "Service level": "How often demand should be met from stock, as a percentage.",
  "Fill rate": "The share of demand met straight from stock.",
  "Time fence": "The near-term window where the plan doesn't create new orders, so the shop floor has a stable plan.",
  "Firm zone": "The near-term window where planned orders are turned into firm orders.",
  Pegging: "The link from each order to the demand it serves.",
  "Shadow price": "What one more unit of a limit (an hour of capacity, a unit from a supplier) would be worth.",
  NPV: "Net present value: future cash flows discounted to today.",
  WACC: "Weighted average cost of capital: what money costs the company, per year.",
  Changeover: "Time to switch a machine from one product family to another.",
};
