/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Examples */
        get: operations["examples_api_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Example */
        get: operations["example_api_examples__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rules */
        get: operations["rules_api_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schema
         * @description JSON schema of the dataset, including ``x-unit`` / ``x-ref`` field metadata for forms.
         */
        get: operations["schema_api_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Validate */
        post: operations["post_validate_api_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Network */
        post: operations["post_network_api_network_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast Models */
        get: operations["forecast_models_api_forecast_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Forecast */
        post: operations["post_forecast_api_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Release */
        post: operations["post_release_api_forecast_release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Plan */
        post: operations["post_plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestPoint */
        BacktestPoint: {
            /** Origin */
            origin: number;
            /** Step */
            step: number;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Actual */
            actual: number;
            /** Forecast */
            forecast: number;
        };
        /** BomItem */
        BomItem: {
            /** Product */
            product: string;
            /**
             * Qty
             * @description Quantity per output_qty of the parent
             */
            qty: number;
            /**
             * Scrap
             * @description Component scrap: share of the issued quantity lost (issue = need ÷ (1 − scrap))
             * @default 0
             */
            scrap: number;
            /**
             * Operation
             * @description Operation seq that consumes it (default: first)
             */
            operation?: number | null;
        };
        /** BucketOut */
        BucketOut: {
            /** Index */
            index: number;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Label */
            label: string;
        };
        /**
         * BucketSize
         * @enum {string}
         */
        BucketSize: "day" | "week" | "month";
        /** Calendar */
        Calendar: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Workdays
             * @description Working weekdays, 0 = Monday … 6 = Sunday
             */
            workdays?: number[];
            /** Holidays */
            holidays?: string[];
        };
        /** CvSuggestion */
        CvSuggestion: {
            /** Location */
            location: string;
            /** Product */
            product: string;
            /** Current */
            current: number | null;
            /** Suggested */
            suggested: number;
        };
        /** Dataset */
        Dataset: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            settings: components["schemas"]["Settings"];
            /** Calendars */
            calendars?: components["schemas"]["Calendar"][];
            /** Locations */
            locations?: components["schemas"]["Location"][];
            /** Products */
            products?: components["schemas"]["Product"][];
            /** Location Products */
            location_products?: components["schemas"]["LocationProduct"][];
            /** Resources */
            resources?: components["schemas"]["Resource"][];
            /** Production Sources */
            production_sources?: components["schemas"]["ProductionSource"][];
            /** Purchasing Sources */
            purchasing_sources?: components["schemas"]["PurchasingSource"][];
            /** Lanes */
            lanes?: components["schemas"]["TransportLane"][];
            /** Demand */
            demand?: components["schemas"]["DemandRecord"][];
            /** Receipts */
            receipts?: components["schemas"]["ScheduledReceipt"][];
            /** History */
            history?: components["schemas"]["SalesHistory"][];
            forecasting?: components["schemas"]["ForecastSettings"];
            /** Events */
            events?: components["schemas"]["DemandEvent"][];
            /** Npi */
            npi?: components["schemas"]["NpiRule"][];
            /** Overrides */
            overrides?: components["schemas"]["ForecastOverride"][];
        };
        /**
         * DemandEvent
         * @description Something that moves demand for a period: a promotion, a price change, a competitor launch…
         *
         *     Past events mark the history they affected, so the baseline is cleansed of them and their lift
         *     is measured. Future events multiply the baseline forecast by ``1 + lift``. Leave ``lift`` empty
         *     on a future event to use the lift measured on past events of the same kind.
         */
        DemandEvent: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** @default promo */
            kind: components["schemas"]["EventKind"];
            /**
             * Products
             * @description Empty = every product
             */
            products?: string[];
            /**
             * Locations
             * @description Empty = every location
             */
            locations?: string[];
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             * @description Last day of the event (inclusive)
             */
            end: string;
            /**
             * Lift
             * @description Demand change while the event runs: 0.3 = +30 %, −0.2 = −20 %
             */
            lift?: number | null;
        };
        /**
         * DemandKind
         * @enum {string}
         */
        DemandKind: "forecast" | "sales_order";
        /**
         * DemandRecord
         * @description A forecast bucket (≈ PIR) or a firm sales-order schedule line (≈ VBBE).
         */
        DemandRecord: {
            /** Id */
            id?: string | null;
            /**
             * Location
             * @description Customer or stocking location where demand occurs
             */
            location: string;
            /** Product */
            product: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Qty */
            qty: number;
            /** @default forecast */
            kind: components["schemas"]["DemandKind"];
            /**
             * Priority
             * @description 1 = highest; used by promising and constrained plans
             * @default 5
             */
            priority: number;
            /**
             * Period Days
             * @description Forecast only: the record covers [date, date + period_days) and is spread evenly over the working days of that window (PIR splitting). Empty = the whole quantity is due on `date`.
             */
            period_days?: number | null;
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "promo" | "price_change" | "launch" | "competitor" | "store_opening" | "disruption" | "other";
        /** ExampleInfo */
        ExampleInfo: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Locations */
            locations: number;
            /** Products */
            products: number;
        };
        /**
         * ForecastModelId
         * @description Models entered into the forecast competition. See ``scp.demand.models``.
         * @enum {string}
         */
        ForecastModelId: "naive" | "seasonal_naive" | "moving_average" | "ses" | "holt_damped" | "holt_winters" | "croston" | "sba" | "tsb" | "regression" | "combination" | "timesfm";
        /** ForecastModels */
        ForecastModels: {
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            foundation: components["schemas"]["FoundationStatus"];
        };
        /**
         * ForecastOverride
         * @description A consensus adjustment for one period: an absolute quantity or a relative change.
         */
        ForecastOverride: {
            /** Location */
            location: string;
            /** Product */
            product: string;
            /**
             * Date
             * Format: date
             * @description Any date inside the forecast period to adjust
             */
            date: string;
            /**
             * Qty
             * @description Final quantity for the period
             */
            qty?: number | null;
            /**
             * Change
             * @description Relative change to the statistical forecast: 0.1 = +10 %
             */
            change?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Author
             * @default
             */
            author: string;
        };
        /**
         * ForecastPeriod
         * @enum {string}
         */
        ForecastPeriod: "week" | "month";
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Label */
            label: string;
            /** Share */
            share: number;
            /** Statistical */
            statistical: number;
            /**
             * Event Factor
             * @default 1
             */
            event_factor: number;
            /**
             * Events
             * @default []
             */
            events: string[];
            /**
             * Cannibalised
             * @default 0
             */
            cannibalised: number;
            /** Override */
            override: number | null;
            /**
             * Override Reason
             * @default
             */
            override_reason: string;
            /** Final */
            final: number;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
            /** Released Qty */
            released_qty: number;
        };
        /** ForecastResult */
        ForecastResult: {
            /** Ok */
            ok: boolean;
            /**
             * Period
             * @enum {string}
             */
            period: "week" | "month";
            /** Season Length */
            season_length: number;
            /** Periods */
            periods: string[];
            /** Issues */
            issues: components["schemas"]["Issue"][];
            /** Series */
            series: components["schemas"]["Series"][];
            summary: components["schemas"]["Summary"];
            foundation: components["schemas"]["FoundationStatus"];
        };
        /**
         * ForecastSettings
         * @description How the statistical forecast is built and chosen (S/4 guide §4: IBP Demand).
         */
        ForecastSettings: {
            /**
             * @description Time grain of history and forecast
             * @default week
             */
            period: components["schemas"]["ForecastPeriod"];
            /**
             * Season Length
             * @description Periods per seasonal cycle; empty = 52 for weeks, 12 for months
             */
            season_length?: number | null;
            /**
             * Models
             * @description Candidate models. TimesFM is only used when the engine has it installed.
             */
            models?: components["schemas"]["ForecastModelId"][];
            /** @default mase */
            selection_metric: components["schemas"]["SelectionMetric"];
            /**
             * Backtest Origins
             * @description Rolling forecast origins in the backtest
             * @default 6
             */
            backtest_origins: number;
            /**
             * Backtest Horizon
             * @description Periods forecast from each origin; match it to the replenishment lead time
             * @default 4
             */
            backtest_horizon: number;
            /**
             * Min History Periods
             * @description Series shorter than this skip the competition and use a simple average
             * @default 8
             */
            min_history_periods: number;
            /** @default mad */
            outlier_method: components["schemas"]["OutlierMethod"];
            /**
             * Outlier Threshold
             * @description Robust z-score (median / MAD) beyond which a value is clipped
             * @default 4
             */
            outlier_threshold: number;
            /**
             * Abc A
             * @description Cumulative revenue share that closes class A
             * @default 0.8
             */
            abc_a: number;
            /**
             * Abc B
             * @description Cumulative revenue share that closes class B
             * @default 0.95
             */
            abc_b: number;
            /**
             * Xyz X
             * @description Forecast-error CV that closes class X
             * @default 0.5
             */
            xyz_x: number;
            /**
             * Xyz Y
             * @description Forecast-error CV that closes class Y
             * @default 1
             */
            xyz_y: number;
            /**
             * Interval
             * @description Central prediction interval shown with the forecast (0.8 = P10–P90)
             * @default 0.8
             */
            interval: number;
        };
        /** FoundationStatus */
        FoundationStatus: {
            /** Enabled */
            enabled: boolean;
            /** Available */
            available: boolean;
            /** Model */
            model: string;
            /** License */
            license: string;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Label */
            label: string;
            /** Raw */
            raw: number;
            /** Cleaned */
            cleaned: number;
            /** Flag */
            flag: ("event" | "outlier") | null;
            /**
             * Events
             * @default []
             */
            events: string[];
        };
        /** Issue */
        Issue: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
            /** Object Type */
            object_type: string;
            /** Object Id */
            object_id: string;
            /** Message */
            message: string;
            /**
             * Hint
             * @default
             */
            hint: string;
            /** Field */
            field: string | null;
        };
        /** Kpis */
        Kpis: {
            /**
             * Purchase Cost
             * @default 0
             */
            purchase_cost: number;
            /**
             * Production Cost
             * @default 0
             */
            production_cost: number;
            /**
             * Setup Cost
             * @default 0
             */
            setup_cost: number;
            /**
             * Ordering Cost
             * @default 0
             */
            ordering_cost: number;
            /**
             * Transport Cost
             * @default 0
             */
            transport_cost: number;
            /**
             * Handling Cost
             * @default 0
             */
            handling_cost: number;
            /**
             * Holding Cost
             * @default 0
             */
            holding_cost: number;
            /**
             * Total Cost
             * @default 0
             */
            total_cost: number;
            /**
             * Inventory Value Start
             * @default 0
             */
            inventory_value_start: number;
            /**
             * Inventory Value End
             * @default 0
             */
            inventory_value_end: number;
            /**
             * Inventory Value Avg
             * @default 0
             */
            inventory_value_avg: number;
            /**
             * Orders Make
             * @default 0
             */
            orders_make: number;
            /**
             * Orders Buy
             * @default 0
             */
            orders_buy: number;
            /**
             * Orders Transfer
             * @default 0
             */
            orders_transfer: number;
            /**
             * Independent Demand
             * @default 0
             */
            independent_demand: number;
            /**
             * On Time Qty
             * @default 0
             */
            on_time_qty: number;
            /**
             * On Time Fill Rate
             * @default 1
             */
            on_time_fill_rate: number;
            /**
             * Max Utilization
             * @default 0
             */
            max_utilization: number;
        };
        /** LaneMode */
        LaneMode: {
            /** @default truck_ftl */
            mode: components["schemas"]["TransportMode"];
            /** Transit Days */
            transit_days: number;
            /**
             * Transit Std Days
             * @default 0
             */
            transit_std_days: number;
            /**
             * Cost Per Unit
             * @default 0
             */
            cost_per_unit: number;
            /**
             * Cost Per Kg
             * @default 0
             */
            cost_per_kg: number;
            /**
             * Cost Per M3
             * @default 0
             */
            cost_per_m3: number;
            /**
             * Cost Per Shipment
             * @description Fixed cost per dispatch
             * @default 0
             */
            cost_per_shipment: number;
            /** Vehicle Capacity Kg */
            vehicle_capacity_kg?: number | null;
            /** Vehicle Capacity M3 */
            vehicle_capacity_m3?: number | null;
            /** Capacity Units Per Week */
            capacity_units_per_week?: number | null;
            /**
             * Default
             * @description Mode used by the MRP heuristic (else the first mode)
             * @default false
             */
            default: boolean;
        };
        /** Location */
        Location: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            type: components["schemas"]["LocationType"];
            /**
             * Region
             * @default
             */
            region: string;
            /** Calendar */
            calendar?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Storage Capacity M3 */
            storage_capacity_m3?: number | null;
            /**
             * Handling Cost Per Unit
             * @description Inbound handling cost per base unit received
             * @default 0
             */
            handling_cost_per_unit: number;
        };
        /**
         * LocationProduct
         * @description How one product is planned at one location (≈ S/4 MARC, MRP views 1–4).
         */
        LocationProduct: {
            /** Location */
            location: string;
            /** Product */
            product: string;
            /** @default MTS_CONSUME */
            strategy: components["schemas"]["Strategy"];
            /** @default deterministic */
            mrp_type: components["schemas"]["MrpType"];
            /**
             * On Hand
             * @description Unrestricted stock at planning start
             * @default 0
             */
            on_hand: number;
            /**
             * Unit Cost
             * @description Valuation override
             */
            unit_cost?: number | null;
            lot_sizing?: components["schemas"]["LotSizing"];
            safety_stock?: components["schemas"]["SafetyStockPolicy"];
            /**
             * Safety Time Days
             * @description Plan receipts this many days early
             * @default 0
             */
            safety_time_days: number;
            /**
             * Reorder Point
             * @description reorder_point MRP type trigger
             */
            reorder_point?: number | null;
            /**
             * Max Stock
             * @description MIN_MAX target / excess threshold
             */
            max_stock?: number | null;
            /**
             * Planning Time Fence Days
             * @description No new proposals inside this fence (firming type 1)
             * @default 0
             */
            planning_time_fence_days: number;
            /**
             * Gr Processing Days
             * @description Goods-receipt / putaway time
             * @default 0
             */
            gr_processing_days: number;
            /**
             * Consumption Backward Days
             * @default 7
             */
            consumption_backward_days: number;
            /**
             * Consumption Forward Days
             * @default 7
             */
            consumption_forward_days: number;
            /**
             * Holding Rate
             * @description Annual carrying rate override (default: WACC + spread)
             */
            holding_rate?: number | null;
        };
        /**
         * LocationType
         * @enum {string}
         */
        LocationType: "plant" | "dc" | "warehouse" | "store" | "supplier" | "customer";
        /**
         * LotSizePolicy
         * @enum {string}
         */
        LotSizePolicy: "L4L" | "FIXED" | "EOQ" | "POQ" | "MIN_MAX";
        /** LotSizing */
        LotSizing: {
            /** @default L4L */
            policy: components["schemas"]["LotSizePolicy"];
            /**
             * Fixed Qty
             * @description FIXED: lot size
             */
            fixed_qty?: number | null;
            /**
             * Periods
             * @description POQ: number of buckets each order covers
             */
            periods?: number | null;
            /**
             * Min Qty
             * @description Minimum lot size
             * @default 0
             */
            min_qty: number;
            /**
             * Max Qty
             * @description Maximum lot size (orders are split)
             */
            max_qty?: number | null;
            /**
             * Rounding Qty
             * @description Round lots up to a multiple
             */
            rounding_qty?: number | null;
            /**
             * Ordering Cost
             * @description Fixed cost per order (EOQ)
             * @default 0
             */
            ordering_cost: number;
        };
        /** ModelInfo */
        ModelInfo: {
            id: components["schemas"]["ForecastModelId"];
            /** Label */
            label: string;
            /** Family */
            family: string;
            /** Description */
            description: string;
        };
        /** ModelScore */
        ModelScore: {
            model: components["schemas"]["ForecastModelId"];
            /** Label */
            label: string;
            /** Family */
            family: string;
            /** Eligible */
            eligible: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Mae */
            mae: number | null;
            /** Rmse */
            rmse: number | null;
            /** Mase */
            mase: number | null;
            /** Wape */
            wape: number | null;
            /** Bias */
            bias: number | null;
            /** Rank */
            rank: number | null;
        };
        /**
         * MrpType
         * @enum {string}
         */
        MrpType: "deterministic" | "reorder_point" | "none";
        /** NetEdge */
        NetEdge: {
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Kind */
            kind: string;
            /** Ids */
            ids: string[];
            /** Products */
            products: string[] | null;
            /** Modes */
            modes: string[];
            /** Transit Days */
            transit_days: number | null;
        };
        /** NetLocation */
        NetLocation: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Region */
            region: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Layer */
            layer: number;
            /** Products */
            products: string[];
            /** Resources */
            resources: string[];
            /** Production Sources */
            production_sources: string[];
        };
        /** NetNode */
        NetNode: {
            /** Location */
            location: string;
            /** Product */
            product: string;
            /** Llc */
            llc: number | null;
            /** Options */
            options: components["schemas"]["NetOption"][];
        };
        /** NetOption */
        NetOption: {
            /** Kind */
            kind: string;
            /** Source Id */
            source_id: string;
            /** Upstream */
            upstream: [
                string,
                string
            ][];
        };
        /** NetworkView */
        NetworkView: {
            /** Locations */
            locations: components["schemas"]["NetLocation"][];
            /** Edges */
            edges: components["schemas"]["NetEdge"][];
            /** Nodes */
            nodes: components["schemas"]["NetNode"][];
            /** Cycles */
            cycles: [
                string,
                string
            ][][];
        };
        /** NodeBucket */
        NodeBucket: {
            /** Bucket */
            bucket: number;
            /**
             * Gross Independent
             * @default 0
             */
            gross_independent: number;
            /**
             * Gross Dependent
             * @default 0
             */
            gross_dependent: number;
            /**
             * Scheduled Receipts
             * @default 0
             */
            scheduled_receipts: number;
            /**
             * Planned Receipts
             * @default 0
             */
            planned_receipts: number;
            /**
             * Projected On Hand
             * @default 0
             */
            projected_on_hand: number;
            /**
             * Safety Stock
             * @default 0
             */
            safety_stock: number;
            /**
             * Below Safety
             * @default 0
             */
            below_safety: number;
            /**
             * Shortage
             * @default 0
             */
            shortage: number;
        };
        /** NodePlan */
        NodePlan: {
            /** Location */
            location: string;
            /** Product */
            product: string;
            /** Llc */
            llc: number;
            /** Strategy */
            strategy: string;
            /** Mrp Type */
            mrp_type: string;
            /** Lot Policy */
            lot_policy: string;
            /** Unit Value */
            unit_value: number;
            /** Value Basis */
            value_basis: string;
            /** On Hand */
            on_hand: number;
            /** Safety Stock Method */
            safety_stock_method: string;
            /**
             * Safety Stock Note
             * @default
             */
            safety_stock_note: string;
            /** Lead Time Days */
            lead_time_days: number | null;
            /** Sources */
            sources: string[];
            /** Buckets */
            buckets: components["schemas"]["NodeBucket"][];
            /** Order Ids */
            order_ids: string[];
        };
        /**
         * NpiRule
         * @description New product introduction: forecast a product without history from a like product.
         */
        NpiRule: {
            /**
             * Location
             * @description Where the new product sells
             */
            location: string;
            /**
             * Product
             * @description The new product
             */
            product: string;
            /**
             * Like Product
             * @description Existing product whose demand shape it follows
             */
            like_product: string;
            /**
             * Like Location
             * @description Empty = the same location
             */
            like_location?: string | null;
            /**
             * Scale
             * @description Share of the like product's volume
             * @default 1
             */
            scale: number;
            /**
             * Launch Date
             * Format: date
             */
            launch_date: string;
            /**
             * Ramp Periods
             * @description Periods to ramp linearly from 0 to full volume
             * @default 4
             */
            ramp_periods: number;
            /**
             * Cannibalisation
             * @description Share of the new volume taken from the like product (its forecast is reduced)
             * @default 0
             */
            cannibalisation: number;
        };
        /** Operation */
        Operation: {
            /** Seq */
            seq: number;
            /**
             * Name
             * @default
             */
            name: string;
            /** Resource */
            resource: string;
            /**
             * Setup Hours
             * @description Per order
             * @default 0
             */
            setup_hours: number;
            /**
             * Run Hours Per Unit
             * @description Machine hours per output base unit
             * @default 0
             */
            run_hours_per_unit: number;
            /** Labor Resource */
            labor_resource?: string | null;
            /**
             * Labor Hours Per Unit
             * @description Worker hours per output unit
             * @default 0
             */
            labor_hours_per_unit: number;
            /**
             * Queue Workdays
             * @description Wait + move time after the operation
             * @default 0
             */
            queue_workdays: number;
            /**
             * Parallel Units
             * @description Resource units one order may run on in parallel (default: all units of the resource)
             */
            parallel_units?: number | null;
        };
        /**
         * OutlierMethod
         * @enum {string}
         */
        OutlierMethod: "none" | "mad";
        /** Peg */
        Peg: {
            /**
             * Supply Kind
             * @enum {string}
             */
            supply_kind: "on_hand" | "receipt" | "order";
            /** Supply Id */
            supply_id: string;
            /** Requirement Id */
            requirement_id: string;
            /** Qty */
            qty: number;
        };
        /** PlanException */
        PlanException: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
            /** Message */
            message: string;
            /** Location */
            location: string | null;
            /** Product */
            product: string | null;
            /** Resource */
            resource: string | null;
            /** Order Id */
            order_id: string | null;
            /** Date */
            date: string | null;
            /** Qty */
            qty: number | null;
        };
        /** PlanResult */
        PlanResult: {
            /** Ok */
            ok: boolean;
            /** Currency */
            currency: string;
            /** Carrying Rate */
            carrying_rate: number;
            /** Buckets */
            buckets: components["schemas"]["BucketOut"][];
            /** Nodes */
            nodes: components["schemas"]["NodePlan"][];
            /** Orders */
            orders: components["schemas"]["PlannedOrder"][];
            /** Requirements */
            requirements: components["schemas"]["Requirement"][];
            /** Receipts */
            receipts: components["schemas"]["ScheduledReceiptOut"][];
            /** Pegs */
            pegs: components["schemas"]["Peg"][];
            /** Resources */
            resources: components["schemas"]["ResourcePlan"][];
            /** Exceptions */
            exceptions: components["schemas"]["PlanException"][];
            kpis: components["schemas"]["Kpis"];
            /** Issues */
            issues: components["schemas"]["Issue"][];
        };
        /** PlannedOrder */
        PlannedOrder: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "make" | "buy" | "transfer";
            /** Location */
            location: string;
            /** Product */
            product: string;
            /** Qty */
            qty: number;
            /** Source Id */
            source_id: string;
            /** Origin */
            origin: string | null;
            /**
             * Need Date
             * Format: date
             */
            need_date: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Available Date
             * Format: date
             */
            available_date: string;
            /**
             * Start In Past
             * @default false
             */
            start_in_past: boolean;
            /**
             * Fence Shifted
             * @default false
             */
            fence_shifted: boolean;
            /**
             * Convertible
             * @default true
             */
            convertible: boolean;
            /**
             * Unit Cost
             * @default 0
             */
            unit_cost: number;
            /**
             * Total Cost
             * @default 0
             */
            total_cost: number;
            /** Shipments */
            shipments: number | null;
            /**
             * Delay Days
             * @default 0
             */
            delay_days: number;
            /** Projected Available Date */
            projected_available_date: string | null;
            /**
             * Lot Excess
             * @default 0
             */
            lot_excess: number;
        };
        /** Product */
        Product: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            type: components["schemas"]["ProductType"];
            /**
             * Base Uom
             * @default EA
             */
            base_uom: string;
            /** Conversions */
            conversions?: components["schemas"]["UomConversion"][];
            /**
             * Family
             * @default
             */
            family: string;
            /**
             * Weight Kg
             * @description Gross weight per base unit
             */
            weight_kg?: number | null;
            /**
             * Volume M3
             * @description Volume per base unit
             */
            volume_m3?: number | null;
            /** Shelf Life Days */
            shelf_life_days?: number | null;
            /**
             * Standard Cost
             * @description Override for the computed cost roll-up
             */
            standard_cost?: number | null;
            /**
             * Price
             * @description Default selling price
             */
            price?: number | null;
            /**
             * Setup Group
             * @description Sequence-dependent setup family (colour, allergen, grade…)
             */
            setup_group?: string | null;
        };
        /**
         * ProductType
         * @enum {string}
         */
        ProductType: "FG" | "SFG" | "RM" | "PKG";
        /**
         * ProductionSource
         * @description How to make a product at a plant: BOM + routing (≈ S/4 production version).
         */
        ProductionSource: {
            /** Id */
            id: string;
            /** Location */
            location: string;
            /** Product */
            product: string;
            /**
             * Output Qty
             * @description Base quantity the BOM refers to
             * @default 1
             */
            output_qty: number;
            /** Components */
            components?: components["schemas"]["BomItem"][];
            /** Operations */
            operations?: components["schemas"]["Operation"][];
            /**
             * Assembly Scrap
             * @description Share of started output lost (start = good ÷ (1 − scrap))
             * @default 0
             */
            assembly_scrap: number;
            /**
             * Fixed Lead Time Workdays
             * @description Override the routing-derived production lead time
             */
            fixed_lead_time_workdays?: number | null;
            /**
             * Min Lot
             * @default 0
             */
            min_lot: number;
            /** Max Lot */
            max_lot?: number | null;
            /**
             * Conversion Cost Per Unit
             * @description Cost not captured by resource rates (energy, overhead)
             * @default 0
             */
            conversion_cost_per_unit: number;
            /**
             * Priority
             * @description Lower wins when several sources exist
             * @default 1
             */
            priority: number;
            /**
             * Quota
             * @description Share of requirements
             */
            quota?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /**
         * PurchasingSource
         * @description Who sells us a product, at what price and lead time (≈ info record + source list + quota).
         */
        PurchasingSource: {
            /** Id */
            id: string;
            /**
             * Supplier
             * @description A location of type supplier
             */
            supplier: string;
            /** Product */
            product: string;
            /**
             * Location
             * @description Receiving location
             */
            location: string;
            /**
             * Price
             * @description Price per base unit in `currency`
             */
            price: number;
            /**
             * Currency
             * @description Default: company currency
             */
            currency?: string | null;
            /**
             * Duty Rate
             * @description Import duty/tariff on price
             * @default 0
             */
            duty_rate: number;
            /**
             * Ordering Cost
             * @description Fixed cost per purchase order
             * @default 0
             */
            ordering_cost: number;
            /**
             * Moq
             * @description Minimum order quantity
             * @default 0
             */
            moq: number;
            /**
             * Rounding Qty
             * @description Pack / pallet multiple
             */
            rounding_qty?: number | null;
            /**
             * Lead Time Days
             * @description Supplier processing: PO to dispatch (transit is on the lane)
             */
            lead_time_days: number;
            /**
             * Lead Time Std Days
             * @description Std deviation of the lead time
             * @default 0
             */
            lead_time_std_days: number;
            /**
             * Capacity Per Week
             * @description Supplier capacity
             */
            capacity_per_week?: number | null;
            /**
             * Priority
             * @default 1
             */
            priority: number;
            /** Quota */
            quota?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /**
         * ReceiptKind
         * @enum {string}
         */
        ReceiptKind: "purchase" | "production" | "transfer";
        /** ReleaseRequest */
        ReleaseRequest: {
            dataset: components["schemas"]["Dataset"];
            /** Keys */
            keys?: string[] | null;
        };
        /** ReleaseResponse */
        ReleaseResponse: {
            dataset: components["schemas"]["Dataset"];
            release: components["schemas"]["ReleaseResult"];
        };
        /** ReleaseResult */
        ReleaseResult: {
            /** Records */
            records: number;
            /** Series */
            series: number;
            /** Replaced */
            replaced: number;
            /** Cv Suggestions */
            cv_suggestions: components["schemas"]["CvSuggestion"][];
        };
        /** Requirement */
        Requirement: {
            /** Id */
            id: string;
            /** Location */
            location: string;
            /** Product */
            product: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Qty */
            qty: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "forecast" | "sales_order" | "dependent" | "transfer";
            /** Parent Order */
            parent_order: string | null;
            /**
             * Priority
             * @default 5
             */
            priority: number;
            /**
             * Consumed Forecast
             * @default 0
             */
            consumed_forecast: number;
            /**
             * Past Due
             * @default false
             */
            past_due: boolean;
        };
        /**
         * Resource
         * @description A work center: machine, line, labour pool or tool (≈ S/4 work center / PP-DS resource).
         */
        Resource: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Location */
            location: string;
            /** @default machine */
            kind: components["schemas"]["ResourceKind"];
            /**
             * Units
             * @description Parallel machines, or headcount for labour
             * @default 1
             */
            units: number;
            /**
             * Shifts Per Day
             * @default 1
             */
            shifts_per_day: number;
            /**
             * Hours Per Shift
             * @default 8
             */
            hours_per_shift: number;
            /**
             * Efficiency
             * @description OEE / utilisation: share of shift hours that are productive
             * @default 0.85
             */
            efficiency: number;
            /**
             * Calendar
             * @description Override the location calendar
             */
            calendar?: string | null;
            /**
             * Cost Per Hour
             * @default 0
             */
            cost_per_hour: number;
            /**
             * Overtime Hours Per Day
             * @description Max overtime per unit per workday
             * @default 0
             */
            overtime_hours_per_day: number;
            /**
             * Overtime Cost Per Hour
             * @default 0
             */
            overtime_cost_per_hour: number;
            /**
             * Finite
             * @description Constrain plans by this resource's capacity
             * @default true
             */
            finite: boolean;
        };
        /** ResourceBucket */
        ResourceBucket: {
            /** Bucket */
            bucket: number;
            /** Load Hours */
            load_hours: number;
            /** Capacity Hours */
            capacity_hours: number;
            /** Overtime Hours */
            overtime_hours: number;
            /** Utilization */
            utilization: number;
        };
        /**
         * ResourceKind
         * @enum {string}
         */
        ResourceKind: "machine" | "line" | "labor" | "tool";
        /** ResourcePlan */
        ResourcePlan: {
            /** Resource */
            resource: string;
            /** Location */
            location: string;
            /** Kind */
            kind: string;
            /** Finite */
            finite: boolean;
            /** Buckets */
            buckets: components["schemas"]["ResourceBucket"][];
        };
        /** RuleInfo */
        RuleInfo: {
            /** Code */
            code: string;
            /** Severity */
            severity: string;
            /** Description */
            description: string;
        };
        /**
         * SafetyStockMethod
         * @enum {string}
         */
        SafetyStockMethod: "none" | "fixed" | "days_of_supply" | "service_level" | "fill_rate";
        /** SafetyStockPolicy */
        SafetyStockPolicy: {
            /** @default none */
            method: components["schemas"]["SafetyStockMethod"];
            /**
             * Qty
             * @description fixed: safety stock quantity
             */
            qty?: number | null;
            /**
             * Days
             * @description days_of_supply: forward coverage
             */
            days?: number | null;
            /**
             * Service Level
             * @description service_level / fill_rate target (default: settings)
             */
            service_level?: number | null;
            /**
             * Demand Cv
             * @description Coefficient of variation of WEEKLY demand (forecast error)
             */
            demand_cv?: number | null;
            /**
             * Review Period Days
             * @description Periodic review interval R
             * @default 0
             */
            review_period_days: number;
        };
        /**
         * SalesHistory
         * @description Long-format history row: one product at one location on one date.
         */
        SalesHistory: {
            /** Location */
            location: string;
            /** Product */
            product: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Qty */
            qty: number;
            /** Price */
            price?: number | null;
            /**
             * Promo
             * @default false
             */
            promo: boolean;
        };
        /**
         * ScheduledReceipt
         * @description Firm supply already committed: open PO, released production order, stock in transit.
         */
        ScheduledReceipt: {
            /** Id */
            id: string;
            kind: components["schemas"]["ReceiptKind"];
            /** Location */
            location: string;
            /** Product */
            product: string;
            /** Qty */
            qty: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Source
             * @description Supplier, source or lane id (information)
             */
            source?: string | null;
        };
        /** ScheduledReceiptOut */
        ScheduledReceiptOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Location */
            location: string;
            /** Product */
            product: string;
            /** Qty */
            qty: number;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** Segment */
        Segment: {
            /**
             * Abc
             * @enum {string}
             */
            abc: "A" | "B" | "C";
            /**
             * Xyz
             * @enum {string}
             */
            xyz: "X" | "Y" | "Z";
            /**
             * Pattern
             * @enum {string}
             */
            pattern: "smooth" | "erratic" | "intermittent" | "lumpy" | "none";
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "new" | "mature" | "inactive" | "npi";
            /** Revenue */
            revenue: number;
            /** Revenue Share */
            revenue_share: number;
            /** Adi */
            adi: number | null;
            /** Cv2 */
            cv2: number | null;
            /** Error Cv */
            error_cv: number | null;
            /** Suggested Service Level */
            suggested_service_level: number;
        };
        /**
         * SelectionMetric
         * @enum {string}
         */
        SelectionMetric: "mase" | "wape" | "rmse";
        /** Series */
        Series: {
            /** Key */
            key: string;
            /** Location */
            location: string;
            /** Product */
            product: string;
            segment: components["schemas"]["Segment"];
            /** History */
            history: components["schemas"]["HistoryPoint"][];
            /** Leaderboard */
            leaderboard: components["schemas"]["ModelScore"][];
            champion: components["schemas"]["ForecastModelId"] | null;
            /**
             * Champion Label
             * @default
             */
            champion_label: string;
            /** Fva */
            fva: number | null;
            /**
             * Backtest
             * @default []
             */
            backtest: components["schemas"]["BacktestPoint"][];
            /** Forecast */
            forecast: components["schemas"]["ForecastPoint"][];
            /**
             * Lifts
             * @default {}
             */
            lifts: {
                [key: string]: number;
            };
            /** Sigma One Step */
            sigma_one_step: number | null;
            /** Demand Cv Weekly */
            demand_cv_weekly: number | null;
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** Settings */
        Settings: {
            /**
             * Company Name
             * @default My Company
             */
            company_name: string;
            /**
             * Currency
             * @description ISO 4217 company currency
             * @default INR
             */
            currency: string;
            /**
             * Planning Start
             * Format: date
             * @description First day of the plan ('today' for planning)
             */
            planning_start: string;
            /**
             * Horizon Days
             * @description Planning horizon length in calendar days
             * @default 182
             */
            horizon_days: number;
            /**
             * @description Reporting / periodic lot-sizing bucket
             * @default week
             */
            bucket: components["schemas"]["BucketSize"];
            /**
             * Week Start
             * @description 0 = Monday … 6 = Sunday
             * @default 0
             */
            week_start: number;
            /**
             * Fx Rates
             * @description Company-currency units per 1 unit of foreign currency, e.g. {'USD': 84.2}
             */
            fx_rates?: {
                [key: string]: number;
            };
            /**
             * Wacc
             * @description Weighted average cost of capital, per year
             * @default 0.12
             */
            wacc: number;
            /**
             * Holding Spread
             * @description Storage + insurance + obsolescence on top of WACC, per year
             * @default 0.08
             */
            holding_spread: number;
            /**
             * Default Service Level
             * @default 0.95
             */
            default_service_level: number;
            /** Default Calendar */
            default_calendar?: string | null;
        };
        /**
         * Strategy
         * @description Planning strategy (S/4 guide §5.2).
         * @enum {string}
         */
        Strategy: "MTS" | "MTS_CONSUME" | "MTO" | "ATO";
        /** Summary */
        Summary: {
            /** Series */
            series: number;
            /** Wape */
            wape: number | null;
            /** Bias */
            bias: number | null;
            /** Fva */
            fva: number | null;
            /**
             * Champions
             * @default {}
             */
            champions: {
                [key: string]: number;
            };
            /**
             * Abc
             * @default {}
             */
            abc: {
                [key: string]: number;
            };
            /**
             * Patterns
             * @default {}
             */
            patterns: {
                [key: string]: number;
            };
            /**
             * Total Final
             * @default 0
             */
            total_final: number;
        };
        /** TransportLane */
        TransportLane: {
            /** Id */
            id: string;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /**
             * Products
             * @description Products carried; empty = all
             */
            products?: string[] | null;
            /** Modes */
            modes: components["schemas"]["LaneMode"][];
            /**
             * Priority
             * @default 1
             */
            priority: number;
            /** Quota */
            quota?: number | null;
        };
        /**
         * TransportMode
         * @enum {string}
         */
        TransportMode: "truck_ftl" | "truck_ltl" | "rail" | "sea" | "air" | "courier" | "pipeline";
        /** UomConversion */
        UomConversion: {
            /** Uom */
            uom: string;
            /**
             * Factor
             * @description Base units in one of this UoM (e.g. 1 CS = 12 EA → 12)
             */
            factor: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Issues */
            issues: components["schemas"]["Issue"][];
            /** Blocking */
            blocking: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    examples_api_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleInfo"][];
                };
            };
        };
    };
    example_api_examples__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rules_api_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleInfo"][];
                };
            };
        };
    };
    schema_api_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_validate_api_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dataset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_network_api_network_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dataset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_models_api_forecast_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastModels"];
                };
            };
        };
    };
    post_forecast_api_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dataset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_release_api_forecast_release_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dataset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
